version: "3.8"

services:

  app:
    image: techchallenge14-app
    build: .
    ports:
      - "8080:8080"
      
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: techchallege
      POSTGRES_PASSWORD: techchallegeGP14
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
      
networks:
  postgres_network:
    driver: bridge

